project:
  type: website
  output-dir: docs

website:
  title: "Learn Hugging Face 🤗"
  favicon: images/learn-hf-favicon.png
  repo-url: https://github.com/mrdbourke/learn-huggingface 
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: extras/setup.md
        text: Setup
      - href: extras/glossary.md
        text: Glossary
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Natural Language Processing (NLP)"
        contents:
          - href: notebooks/hugging_face_text_classification_tutorial.ipynb
            text: Text Classification
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



