on:
    workflow_dispatch:
    push:
      branches: main
  
name: Quarto Publish

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2

            - name: Render and Publish
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                target: gh-pages
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Ensure CNAME file (for custom domain usage)
              run: |
                echo "your-custom-domain.com" > CNAME
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add CNAME
                git commit -m "Add CNAME file"
                git push origin gh-pages